### ISSUE TITLE
Issue with add_tags and vasp_input_set

### ISSUE THREAD

**Issue by blondegeek** [hackingmaterials/MatMethods#44]
Howdy,
When I run the following:
```
from pymatgen.core.structure import Structure
from matmethods.vasp.fireworks.core import OptimizeFW
from fireworks.core.firework import Workflow
from pymatgen.io.vasp.sets import MPStaticSet
from pymatgen.matproj.rest import MPRester
from matmethods.vasp.vasp_powerups import add_tags

a = MPRester()
Si = a.query({'material_id':'mp-149'},['structure']).pop()['structure']

tags = ['test_1','test_2']

wf = [OptimizeFW(Si,name="test",vasp_cmd='>>vasp_cmd<<',db_file='>>db_file<<')]
wf = Workflow(wf)
add_tags(wf,tags)
```
I get this error:
```
Traceback (most recent call last):
  File "debug_tags.py", line 18, in <module>
    add_tags(wf,tags)
  File "/Users/tesssmidt/Dropbox/test_pymatgen/venv/src/matmethods-tess/matmethods/vasp/vasp_powerups.py", line 316, in add_tags
    return Workflow.from_dict(wf_dict)
  File "/Users/tesssmidt/Dropbox/test_pymatgen/venv/src/fireworks-tess/fireworks/core/firework.py", line 1120, in from_dict
    return Workflow([Firework.from_dict(f) for f in m_dict['fws']],
  File "/Users/tesssmidt/Dropbox/test_pymatgen/venv/src/fireworks-tess/fireworks/utilities/fw_serializers.py", line 147, in _decorator
    new_args[0] = {k: _recursive_load(v) for k, v in args[0].items()}
  File "/Users/tesssmidt/Dropbox/test_pymatgen/venv/src/fireworks-tess/fireworks/utilities/fw_serializers.py", line 147, in <dictcomp>
    new_args[0] = {k: _recursive_load(v) for k, v in args[0].items()}
  File "/Users/tesssmidt/Dropbox/test_pymatgen/venv/src/fireworks-tess/fireworks/utilities/fw_serializers.py", line 108, in _recursive_load
    return {k: _recursive_load(v) for k, v in obj.items()}
  File "/Users/tesssmidt/Dropbox/test_pymatgen/venv/src/fireworks-tess/fireworks/utilities/fw_serializers.py", line 108, in <dictcomp>
    return {k: _recursive_load(v) for k, v in obj.items()}
  File "/Users/tesssmidt/Dropbox/test_pymatgen/venv/src/fireworks-tess/fireworks/utilities/fw_serializers.py", line 111, in _recursive_load
    return [_recursive_load(v) for v in obj]
  File "/Users/tesssmidt/Dropbox/test_pymatgen/venv/src/fireworks-tess/fireworks/utilities/fw_serializers.py", line 103, in _recursive_load
    return load_object(obj)
  File "/Users/tesssmidt/Dropbox/test_pymatgen/venv/src/fireworks-tess/fireworks/utilities/fw_serializers.py", line 309, in load_object
    return cls_.from_dict(obj_dict)
  File "/Users/tesssmidt/Dropbox/test_pymatgen/venv/src/fireworks-tess/fireworks/utilities/fw_serializers.py", line 147, in _decorator
    new_args[0] = {k: _recursive_load(v) for k, v in args[0].items()}
  File "/Users/tesssmidt/Dropbox/test_pymatgen/venv/src/fireworks-tess/fireworks/utilities/fw_serializers.py", line 147, in <dictcomp>
    new_args[0] = {k: _recursive_load(v) for k, v in args[0].items()}
  File "/Users/tesssmidt/Dropbox/test_pymatgen/venv/src/fireworks-tess/fireworks/utilities/fw_serializers.py", line 106, in _recursive_load
    return json.loads(json.dumps(obj), cls=MontyDecoder)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 352, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "/Users/tesssmidt/Dropbox/test_pymatgen/venv/lib/python2.7/site-packages/monty/json.py", line 187, in decode
    return self.process_decoded(d)
  File "/Users/tesssmidt/Dropbox/test_pymatgen/venv/lib/python2.7/site-packages/monty/json.py", line 177, in process_decoded
    return cls_.from_dict(data)
  File "/Users/tesssmidt/Dropbox/test_pymatgen/venv/lib/python2.7/site-packages/monty/json.py", line 73, in from_dict
    return cls(**kwargs)
  File "/Users/tesssmidt/Dropbox/test_pymatgen/venv/src/pymatgen-tess/pymatgen/io/vasp/sets.py", line 421, in __init__
    structure, MPRelaxSet.CONFIG, **kwargs)
  File "/Users/tesssmidt/Dropbox/test_pymatgen/venv/src/pymatgen-tess/pymatgen/io/vasp/sets.py", line 239, in __init__
    structure = structure.get_sorted_structure()
AttributeError: 'dict' object has no attribute 'get_sorted_structure'
```

Can you reproduce this error?

Thanks!
Tess

**Comment by computron** [comment]
You should look at the error trace ...

Your code thinks that "structure" is a dict

You should convert it to a Structure
either just use the "get_structure_by_material_id" method in MPRester, or use Structure.from_dict() (or one of the automatic object loading function in pymatgen) to convert your dict into a Structure

**Comment by blondegeek** [comment]
I checked the type of Si, it's <class 'pymatgen.core.structure.Structure'>.

**Comment by computron** [comment]
Ok I tried running your code. I didn't get any errors

Please make sure your codes are up to date. If you still having problems please report the versions of all your codes

**Comment by computron** [comment]
also, at the end, make sure you do

wf = add_tags(wf,tags)

(remember our conversation about the function not modifying the workflow in place)

**Comment by blondegeek** [comment]
It was a monty issue. I was using 0.8.7. Works just fine with 0.9.5.

**Comment by computron** [comment]
Ok note that the setup.py / requirements file for MatMethods required monty
> 0.9.0. If you installed MatMethods with pip or did Github plus python
setup.py develop, it should have worked …

Anyway glad you figured it out


On September 22, 2016 at 2:54:33 PM, Tess (notifications@github.com) wrote:

It was a monty issue. I was using 0.8.7. Works just fine with 0.9.5.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/hackingmaterials/MatMethods/issues/44#issuecomment-249039576>,
or mute the thread
